config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'sessions/new'
  get 'static_pages/mypage'
  get 'static_pages/about'
  get 'static_pages/profile'
  get 'static_pages/sample'
  get '/signup', to:'users#new'
  get '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'
  get '/sample', to: 'static_pages#sample'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
      
  resources :microposts, only: [:create, :destroy, :new]
  resources :relationships,   only: [:create, :destroy]
  resources :searches, only: [:new, :index]
  resources :finds, only: [:new, :index]
end

app/controllers/finds_controller.rb
class FindsController < ApplicationController

    def new
    end

    def index
        q = {
            'appid' => ENV['YAHOO_API'],
            'query' => params[:name],
            'results' => 20,
            'gc' => '01',
            'output' =>  'json'
          }
          client = HTTPClient.new
          
          request = client.get(ENV['YAHOO_URI'], q)
          @api_params = JSON.parse(request.body)
    end

end

app/helpers/finds_helper.rb
module FindsHelper
end

app/views/finds/index.html.erb
<% provide(:title, "search restaurants")%>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
        
      <h2>検索キーワード</h2>
      <h2><%= params[:name]%></h2>
      
      <%= link_to "再度検索" , new_find_path , class: 'back_button btn btn-default'%>
      
      <% if @api_params['ResultInfo']['Count'] == 0%>
        <p>検索結果がありません</p>
      <% else %>
        <ul class="nav nav-pills nav-stacked">
        <% @api_params['Feature'].each do |n| %>
          <li role="presentation">
            <%= link_to n['Name'] + n['Property']['Address'],  new_micropost_path(api_title: n['Name'] ,api_address: n['Property']['Address']) %>
          </li>
        <% end %>
        </ul>
      <% end %>
      

    </div>
  </div>
  
  
  

app/views/finds/new.html.erb
<% provide(:title, "search restaurants")%>

<div class="col-md-6 col-md-offset-3">
    <h3>飲食店を検索</h3>
    
    <p>キーワード, キーワード + エリアで検索してください</p>
    <p>例 ( 百香亭 , 牛角 つくば) </p>

    <%= form_with url: finds_path, method: :get, local: true do |f| %>
        <div class="form-group">
            <%= f.label :name,"キーワード" %>
            <%= f.text_field :name,class: 'form-control'%>
        </div>
        <%= f.submit "検索",  class: 'btn btn-primary' %>
    <% end %>
    
    <%= link_to "戻る" , static_pages_mypage_path , class: 'btn btn-default finds_new_btn'%>
    <%= link_to "直接入力", new_micropost_path , class: 'btn btn-default finds_new_btn'%>

</div>