config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'sessions/new'
  get 'static_pages/mypage'
  get 'static_pages/about'
  get 'static_pages/profile'
  get 'static_pages/sample'
  get '/signup', to:'users#new'
  get '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'
  get '/sample', to: 'static_pages#sample'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
      
  resources :microposts, only: [:create, :destroy, :new]
  resources :relationships,   only: [:create, :destroy]
  resources :searches, only: [:new, :index]
  resources :finds, only: [:new, :index]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :mypage]
  
  def home
    render layout: false
  end

  def about
    render layout: false
  end
  
  def sample
  end
  
  def mypage
    if logged_in?
      # @microposts = current_user.microposts.paginate(page: params[:page])
      @feed_items = current_user.feed.paginate(page:params[:page])
    end
  end
  
  def profile
    @microposts = current_user.microposts.paginate(page: params[:page])
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>About</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  
  <!--application.html.erbは反映されないようにコントローラーで設定-->
  <body>
    <div class="container intro">
      <h1> このアプリケーションについて </h1>
      
      <div class="col-md-6">
        <%= image_tag 'intro2.png', class:"intro1"%>
        <div class="content2">
          
          <h2>自分用の飲食店の記録に</h2>
            <p>
              「今日のご飯どこへ行こう」 </br>
              「いろいろ飲食店は知っているけど、なかなか決まらない」</br>
              このような経験はありませんか？</br>
            </p>
            <p>
              このアプリケーションでは飲食店のレビューや写真、</br>
              満足度を記録することができます。
            </p>
            <p>
              今までに行った飲食店の思い出の記録し、
              再び振り返る際に便利なアプリケーションです。
            </p>
        </div>
            <div class="b">
              <%= link_to "ログイン", login_path, class:"home2 btn--white btn--radius"%>
            </div>
            
            <div class="b">
              <%= link_to "新規登録", signup_path, class:"home2 btn--white btn--radius"%>
            </div>
            <div class="b">
              <%= link_to "ホーム画面へ",   '/' , class:"home2 btn--white btn--radius"%>
            </div>
  
      </div>
      
      <div class="col-md-6">
        <div class="content">


          <h2>友人との飲食店の共有に</h2>
          <p>
            今まで行ったことのない新しいお店に行ってみたい。
          </p>
          <p>
            不特定多数の口コミ共有アプリケーションでは、</br>
            ・投稿者がどんなひとなのかわからない</br>
            ・情報が多すぎてどれを参考にするべきかわからない</br>
            しかし、友人からの口コミなら安心できる
          </p>
          <p>
            このような想いからこのアプリケーションを開発しました。
          </p>
          <p>
            友人と一緒に素敵な飲食店を共有してみてください。
          </p>
            
        </div>
        <%= image_tag 'intro2.png', class:"intro2"%>
      </div>
    </div>
    
    <div class="under">

    </div>
    
  </body>
</html>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShareGourmet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all',
                              'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application',
    'data-turbolinks-track': 'reload' %>
  </head>
  <!--application.html.erbは反映されないようにコントローラーで設定-->
  <body class="space">
    <div class="container">
      <h1 class="top"> ShareGourmet </h1>
      <h2> フォロワー間に限定した飲食店クチコミ共有アプリケーション</h2>
      
      <div class="b">
        <%= link_to "このアプリケーションについて", '/static_pages/about', class:"home2 btn--white btn--radius"%>
      </div>
      
      <div class="b">
        <%= link_to "ログイン", login_path, class:"home2 btn--white btn--radius"%>
      </div>
      
      <div class="b">
        <%= link_to "新規登録", signup_path, class:"home2 btn--white btn--radius"%>
      </div>

    
      <!--デバック用の表示　開発環境のみ-->
      
      <%= debug(params) if Rails.env.development? %>
    </div>
    
    
  </body>
</html>

app/views/static_pages/mypage.html.erb
<% provide(:title, current_user.name ) %>

<div class="row">
  <div class="col-md-3 sidebar sticky">
    
    <div class="prof_margin">
      <% if current_user.image.attached? %>
        <%= image_tag current_user.image, class:"prof_image"%>
      <% else%>
        <%= image_tag "default.png", class:"prof_default"%>
      <% end%>      
    </div>
    
    <div class="b">
      <p class="name"><%= current_user.name%></p>
      <p><%= render 'shared/stats' %></p>
    </div>
    
    
    
    <div class="b">
      <%= link_to "プロフィール", "/static_pages/profile", class:"home btn--white btn--radius"%>
    </div>
  

    
    <div class="b">
      <%= link_to "ログアウト", logout_path, class:"home btn--white btn--radius"%>
    </div>
    
    <div class="b">
      <%= link_to "新規投稿", new_find_path , class:"home btn--orange btn--radius"%>
    </div>
    
  </div>
  <!--</aside>-->
  
  <!--メイン部分-->
  <div class="col-md-7">
    <% if current_user.microposts.any? %>
      <ol class="microposts">
        <%= render @feed_items %>
      </ol>
      <%= will_paginate @feed_items, params: { controller: :static_pages, action: :mypage } %>
    <% end %>
  </div>
  
  <div class="col-md-2 right-sidebar sticky">
    <div class="b">
      <%= link_to "ユーザー検索", new_search_path, class:"home btn--white btn--radius" %>
    </div>
  </div>
  
  

</div>

app/views/static_pages/profile.html.erb
<% provide(:title, current_user.name )%>

<div class="row">
  <div class="col-md-3 sidebar sticky">

    <div class="prof_margin">
      <% if current_user.image.attached? %>
        <%= image_tag current_user.image, class:"prof_image"%>
      <% else%>
        <%= image_tag "default.png", class:"prof_default"%>
      <% end%>      
    </div>
    
    <div class="b">
      <p class="name"><%= current_user.name%></p>
      <p><%= render 'shared/stats' %></p>
    </div>
    
    <div class="b">
      <%= link_to "ホーム", "/static_pages/mypage", class:"home btn--white btn--radius"%>
    </div>
  
    <div class="b">
      <%= link_to "設定", edit_user_path(current_user), method: :get, class:"home btn--white btn--radius"%>
    </div>

    
    <div class="b">
      <%= link_to "ログアウト", logout_path, method: :delete , class:"home btn--white btn--radius"%>
    </div>
    
    <div class="b">
      <%= link_to "新規投稿", new_find_path , class:"home btn--orange btn--radius"%>
    </div>
    
  </div>
    
    
    
    
  <div class="col-md-7">
    <% if current_user.microposts.any? %>
      <h3><%= current_user.microposts.count %>件の投稿</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
  
  <div class="col-md-2 right-sidebar sticky">
    <div class="b">
      <%= link_to "ユーザー検索", new_search_path, class:"home btn--white btn--radius" %>
    </div>
  </div>

</div>

app/views/static_pages/sample.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <script src="https://cdn.jsdelivr.net/npm/p5@1.2.0/lib/p5.js"></script>
  <script src="api/sketch.js"></script>
</head>

<body>
  <h2>Wikipedia バックリンクの一覧</h2>
  <p>
    単語：<input id='input' value="" />
  </p>
</body>

</html>