config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'sessions/new'
  get 'static_pages/mypage'
  get 'static_pages/about'
  get 'static_pages/profile'
  get 'static_pages/sample'
  get '/signup', to:'users#new'
  get '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'
  get '/sample', to: 'static_pages#sample'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
      
  resources :microposts, only: [:create, :destroy, :new]
  resources :relationships,   only: [:create, :destroy]
  resources :searches, only: [:new, :index]
  resources :finds, only: [:new, :index]
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  
  def new
  end
  
  def index
    if params[:keyword].present?
      @users = User.where('name LIKE ?', "%#{params[:keyword]}%")
    else
      @users = User.none
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/index.html.erb
<% provide(:title, "search restaurants")%>
  <div class="row">
    <div class="col-md-3 sidebar sticky">
      <div class="b">
        <%= link_to "戻る" , new_search_path , class: 'home btn--white btn--radius'%>
        <%= link_to "全ユーザー", users_path , class: 'home btn--white btn--radius'%>        
      </div>
    </div>
    <div class="col-md-7">
        
      <h2>検索キーワード</h2>
      <h2><%= params[:keyword]%></h2>
      <% if @users.present? %>
        <ul class="users">
          <% @users.each do |user| %>
            <%= render user %>
          <% end %>
        </ul>
      <% else %>
        <h2>見つかりません</h2>
      <% end %>

    </div>
    <div class="col-md-2 right-sidebar sticky">
    </div>
  </div>
  
  
  

app/views/searches/new.html.erb
<% provide(:title, "search restaurants")%>
  <div class="row">
    <div class="col-md-3 sidebar sticky">
      <div class="b">
        <%= link_to "戻る" , static_pages_mypage_path , class: 'home btn--white btn--radius'%>
         
      </div>
    </div>
    <div class="col-md-7">
      <h2>ユーザーを検索</h2>
  
      <%= form_with url: searches_path, method: :get, local: true do |f| %>
        <div class="form-group form_size">
          <%= f.label :keyword,"keyword" %>
          <%= f.text_field :keyword,class:'form-control'%>
          <%= f.submit "検索",  class: 'btn btn-primary' %>
        </div>
      <% end %>
      <%= link_to "Developer's Account (taigamur)" ,  user_path(id: 1), class:"btn btn-outline-secondary user_searches_link" %>
  </div>
  <div class="col-md-2 right-sidebar sticky">
  </div>
</div>
  